config/routes.rb
Rails.application.routes.draw do

  root to: 'static_pages#root'

  namespace :api, defaults: {format: :json} do
    resources :activities
  end

  resources :users, only: [:new, :create, :index, :show, :update] do
    resource :follow, only: [:create, :destroy]
  end

  resources :attendees, only: [:new, :create, :index, :show, :destroy]
  resource :session, only: [:new, :create, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  email               :string           not null
#  password_digest     :string           not null
#  session_token       :string           not null
#  first_name          :string           not null
#  last_name           :string           not null
#  profile_picture_url :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class User < ActiveRecord::Base
  validates :email, :password_digest, :first_name, :last_name, :session_token,
    presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :in_follows, class_name: "Follow", foreign_key: "followee_id"
  has_many :out_follows, class_name: "Follow", foreign_key: "follower_id"
  has_many :followers, through: :in_follows, source: :follower
  has_many :followees, through: :out_follows, source: :followee
  has_many :activities, foreign_key: :owner_id
  has_many :attendee_activities,
    class_name: "Attendee",
    foreign_key: :user_id
  has_many :attending_activities,
    through: :attendee_activities,
    source: :activity


  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil unless user && user.is_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def self.find_by_search_fragment(search_fragment)
    search_fragment = search_fragment.downcase
    results = self.where("LOWER(display_name) LIKE ?", "%#{search_fragment}%")
  end

  def followed_by?(user)
    followers.include?(user)
  end

  def find_followers
    followers
  end

  def self.find_followee(id, current_user)
    user = User.find(id)
    is_follower = user.followed_by?(current_user)
    followee = {id: user.id, display_name: user.display_name, followee: is_follower}
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.display_name = @user.first_name.downcase.capitalize + " " +
                            @user.last_name.downcase.capitalize
    @user.profile_photo_url = "http://res.cloudinary.com/dbw79utiw/image/upload/v1445805052/i6qkba2yfqaf6ziadxrp.jpg"
    @user.cover_photo_url = "https://res.cloudinary.com/dbw79utiw/image/upload/x_108,y_31,w_1879,h_1879,c_crop/v1445817847/swah17i9e0zdixwf5qpq.png"

    if @user.save
      sign_in(@user)
      redirect_to :root
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    if params[:user][:search_fragment]
      @users = User.find_by_search_fragment(params[:user][:search_fragment]).includes(:followees)
    elsif params[:user][:all_followers]
      @users = current_user.find_followers.includes(:followers)
    elsif params[:user][:all_following]
      @users = current_user.followees.includes(:followers)
    end
    @users
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      render json: @user
    end
  end

  private
  def user_params
    params.require(:user).permit(:password,
                                 :first_name,
                                 :last_name,
                                 :display_name,
                                 :id,
                                 :email,
                                 :search_fragment,
                                 :current_user,
                                 :profile_photo_url,
                                 :profile_photo_object,
                                 :cover_photo_url,
                                 :profile_photo_object
                                 )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<body class="unique">
	<div class="text-center" style="padding:100px 0">
		<div class="login-form-background">
			<div class="logo">sign up</div>
			<div class="login-form-1">
				<form id="register-form" class="text-left" action="<%= users_url %>" method="post">
		      <input type="hidden"
		             name="authenticity_token"
		             value="<%= form_authenticity_token %>">
					<div class="login-form-main-message"></div>
					<div class="main-login-form">
						<div class="login-group">
							<div class="form-group">
								<label for="reg_username" class="sr-only">First Name</label>
								<input type="text" class="form-control" id="reg_username" name="user[first_name]" placeholder="first name">
							</div>
							<div class="form-group">
								<label for="reg_email" class="sr-only">Last Name</label>
								<input type="text" class="form-control" id="reg_email" name="user[last_name]" placeholder="last name">
							</div>
							<div class="form-group">
								<label for="reg_email" class="sr-only">Email</label>
								<input type="text" class="form-control" id="reg_fullname" name="user[email]" placeholder="email">
							</div>
		          <div class="form-group">
								<label for="reg_password" class="sr-only">Password</label>
								<input type="password" class="form-control" id="reg_password" name="user[password]" placeholder="password">
							</div>
						</div>
						<button type="submit" class="login-button"><i class="glyphicon glyphicon-chevron-right"></i></button>
					</div>
					<div class="etc-login-form">
						<p>already have an account? <%= link_to 'sign in', new_session_url %></p>
					</div>
					<div class="etc-login-form">
						<p>not ready to sign up?
							<%= link_to 'sign in as a guest', session_path(
									{user: {email: 'guestuser@guest.user', password: 'password'}}),
									method: :post%>
						</p>
					</div>
				</form>
			</div>
		</div>
	</div>
<body>